name: "Demo 1 - UNO Q Smart Solar Pannel"
description: A small solar pannel system that orient solar pannels automatically and protects and autoclean them using the Arduino UNO Q advanced Edge AI Features.
ports: []
bricks:
- arduino:weather_forecast: {}
- arduino:web_ui: {}
- arduino:dbstorage_tsstore: {}
icon: 🌞
